version: '3.9'

services:
  mysql:
    container_name: 'mysql82-db'
    image: 'mysql:8.2.0'
    env_file:
      - '.env'
    ports: 
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
      - './backup:/var/lib/mysql-backup'
